language: clojure
lein: lein2
#before_script: "ls ~/.lein/ && cat ~/.lein/profiles.clj && lein plugin install lein-immutant 0.12.0"
before_script: ./setup_profiles.sh
script: lein2 immutant install && lein2 immutant test
